name: gitignore-in
author: Yui KITSU
description: |
  Run gitignore-in command and if .gitignore is updated, generate pull request.
branding:
  icon: file-minus
  color: white

inputs:
  branch_name:
    description: |
      Branch name to create pull request.
      Default: gitignore-in
    required: false
    default: gitignore-in
  base_branch:
    description: |
      Base branch name to create pull request.
      Default: main
    required: false
    default: main
outputs:
  pull-request-number:
    description: Pull request number.
    value: ${{ steps.create_pull_request.outputs.pull-request-number }}
  pull-request-url:
    description: Pull request URL.
    value: ${{ steps.create_pull_request.outputs.pull-request-url }}
  pull-request-operation:
    description: |
      The pull request operation performed by the action, `created`, `updated` or `closed`.
    value: ${{ steps.create_pull_request.outputs.pull-request-operation }}
  pull-request-head-sha:
    description: |
      The SHA of the head commit of the pull request.
    value: ${{ steps.create_pull_request.outputs.pull-request-head-sha }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ inputs.base_branch }}

    - uses: gitignore-in/install-gibo@v0.1.0
    - run: |
        tmpdir=$(mktemp -d)
        cd "${tmpdir}"
        version=v0.2.0
        # TODO: support other platform
        target=gitignore-in-x86_64-unknown-linux-gnu-v0.2.0.tar.gz
        url="https://github.com/gitignore-in/gitignore-in/releases/download/${version}/${target}"
        wget "${url}"
        tar -xzf "${target}"
        cp gitignore.in /usr/local/bin
        chmod +x /usr/local/bin/gitignore.in
        rm -rf "${tmpdir}"
      shell: bash

    - name: run gitignore.in
      run: gitignore.in
      shell: bash

    - name: check .gitignore
      id: check
      run: git diff --name-only .gitignore | grep .gitignore || echo '' > /dev/stdout
      shell: bash

    - uses: peter-evans/create-pull-request@v5
      id: create_pull_request
      with:
        branch: ${{ inputs.branch_name }}
        base: ${{ inputs.base_branch }}
        commit-message: Update .gitignore by gitignore.in
        delete-branch: true
        title: Update .gitignore
        body: |
          Update .gitignore by gitignore.in
      env:
        GH_TOKEN: ${{ github.token }}
